#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -w /app \
  -v $(pwd):/app \
  -v pgdata_rebase_labs:/var/lib/postgresql/data \
  -v rubygems_rebase_labs:/usr/local/bundle \
  --network rebase-labs \
  -p 3000:3000 \
  ruby \
  bash -c "ruby server.rb"
  #bash -c "gem install bundler && bundle install &&gem install rack sinatra puma && ruby server.rb"